language: perl
perl:
  - "5.8"
  - "5.16"
  - "5.24"
os:
  - linux
  - osx
before_install:
    - curl -L https://cpanmin.us | perl - App::cpanminus
install:
    - cpanm -n -q --installdeps .
script:
    - prove -l -r t/
