language: perl
perl:
  - "5.8"
  - "5.16"
  - "5.24"
os:
  - linux
  - osx
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install perlbrew; perlbrew install-cpanm; fi
install:
    - cpanm -n -q --installdeps .
script:
    - prove -l -r t/
